---
all:
  hosts:
    el-instance:
      ansible_host: 62.84.121.141
    k-instance:
      ansible_host: 84.201.160.96
    application-instance:
      ansible_host: 84.201.165.36
  vars:
    ansible_connection: ssh
    ansible_user: solomatinkirill
elasticsearch:
  hosts:
    el-instance:
kibana:
  hosts:
    k-instance:
app:
  host:
    application-instance:
