---
all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_password: GetOff100
elasticsearch:
  hosts:
    el-instance:
      ansible_host: 172.22.77.91
kibana:
  hosts:
    ki-instance:
      ansible_host: 172.22.79.16
filebeat:
  hosts:
    fb-instance:
      ansible_host: 172.22.65.18